package com.max.example.files.entities;

public enum StudentStatus {
    STUDENT_ROLE_REGISTRATION,
    STUDENT_REGION_REGISTRATION, STUDENT_SCHOOL_REGISTRATION,
    STUDENT_CLASS_REGISTRATION,
    STUDENT_IN_ACTION,
    STUDENT_CHOOSE,

    STUDENT_CHOOSED_CALCULATOR,
    STUDENT_CHOSED_ADD_HOMEWORK,
    STUDENT_CHOSED_SEND_ATTENTION,
    STUDENT_CHOSED_SCHEDULE_NODE,
    STUDENT_CHOSED_SEND_HOMEWORK_ATTENTION,
    STUDENT_CHOOSED_SEND_SCHEDULE_CHANGES_ATTENTION,
    STUDENT_CHOOSED_RE_REGISTRATION
}
