package com.max.example.files.entities;

public enum StudentStatus {
    STUDENT_REGISTRATION, STUDENT_ROLE_REGISTRATION,
    STUDENT_REGION_REGISTRATION, STUDENT_SCHOOL_REGISTRATION,
    STUDENT_CLASS_REGISTRATION
}
